import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles(
  {
    root: {
      flex: '1 0 0',
      overflow: 'auto',
    },
    // h1: {
    //   margin: `0 0 ${vars.gap.M}`,
    //   padding: `${vars.gap.S} ${vars.gap.M}`,
    //   fontSize: vars.fontSize.XL,
    //   fontWeight: vars.fontWeight.bold,
    //   color: palette.font.first,
    //   lineHeight: vars.lineHeight.regular,
    //   background: palette.first.extraLight,
    //   borderLeft: `4px solid ${palette.first.main}`,
    //   borderRadius: vars.radius.main,
    //   boxShadow: vars.boxShadow.button,
    // },
    // h2: {
    //   margin: `${vars.gap.L} 0 ${vars.gap.S}`,
    //   paddingTop: vars.gap.S,
    //   fontSize: vars.fontSize.L,
    //   fontWeight: vars.fontWeight.bold,
    //   color: palette.font.first,
    //   lineHeight: vars.lineHeight.regular,
    //   borderTop: `1px solid ${palette.first.light}`,
    // },
    // h3: {
    //   margin: `${vars.gap.S} 0 0`,
    //   padding: `${vars.gap.S} ${vars.gap.M}`,
    //   fontSize: vars.fontSize.M - 1,
    //   fontWeight: vars.fontWeight.semiBold,
    //   color: palette.font.first,
    //   background: palette.bg.light,
    //   borderRadius: vars.radius.main,
    //   boxShadow: vars.boxShadow.button,
    // },
    // h4: {
    //   margin: `${vars.gap.S} 0 ${vars.gap.SS}`,
    //   fontSize: vars.fontSize.main,
    //   fontWeight: vars.fontWeight.semiBold,
    //   color: palette.font.second,
    // },
    // p: {
    //   margin: 0,
    // },
    // a: {
    //   color: palette.first.main,
    //   textDecoration: 'underline',
    //   '&:hover': {
    //     color: palette.first.dark,
    //   },
    // },
    // ul: {
    //   margin: `0 0 ${vars.gap.S}`,
    //   padding: `${vars.gap.S} ${vars.gap.M} ${vars.gap.S} calc(${vars.gap.M} + ${vars.gap.S})`,
    //   background: `${palette.add.extraLight}66`,
    //   borderRadius: vars.radius.main,
    //   listStyleType: 'disc',
    // },
    // ol: {
    //   paddingLeft: vars.gap.M,
    //   margin: `0 0 ${vars.gap.S}`,
    //   background: `${palette.first.extraLight}55`,
    //   borderRadius: vars.radius.main,
    //   padding: `${vars.gap.S} ${vars.gap.M} ${vars.gap.S} calc(${vars.gap.M} + ${vars.gap.S})`,
    //   listStyleType: 'decimal',
    // },
    // li: {
    //   marginBottom: vars.gap.SS,
    // },
    // pre: {
    //   background: palette.dark.dark,
    //   borderRadius: vars.radius.main,
    //   padding: vars.gap.M,
    //   overflowX: 'auto',
    //   margin: `0 0 ${vars.gap.S}`,
    //   boxShadow: vars.boxShadow.button,
    // },
    // code: {
    //   fontFamily: 'monospace',
    //   fontSize: vars.fontSize.S,
    //   color: palette.font.light,
    // },
    // inlineCode: {
    //   fontFamily: 'monospace',
    //   fontSize: vars.fontSize.S,
    //   background: palette.first.extraLight,
    //   borderRadius: vars.radius.SS,
    //   padding: `2px ${vars.gap.SS}`,
    //   color: palette.font.first,
    // },
    // blockquote: {
    //   borderLeft: `4px solid ${palette.first.main}`,
    //   padding: `${vars.gap.S} ${vars.gap.M}`,
    //   margin: `0 0 ${vars.gap.S}`,
    //   color: palette.font.dark,
    //   background: `${palette.first.extraLight}55`,
    //   borderRadius: vars.radius.main,
    // },
    // hr: {
    //   border: 'none',
    //   borderTop: `1px solid ${palette.dark.extraLight}`,
    //   margin: `${vars.gap.M} 0`,
    // },
    // tableWrap: {
    //   overflowX: 'auto',
    //   marginBottom: vars.gap.S,
    // },
    // table: {
    //   width: '100%',
    //   borderCollapse: 'collapse',
    //   fontSize: vars.fontSize.S,
    //   background: palette.bg.light,
    //   borderRadius: vars.radius.main,
    //   overflow: 'hidden',
    //   boxShadow: vars.boxShadow.button,
    // },
    // th: {
    //   background: palette.first.main,
    //   color: palette.font.light,
    //   fontWeight: vars.fontWeight.semiBold,
    //   padding: `${vars.gap.SS} ${vars.gap.S}`,
    //   border: `1px solid ${palette.first.dark}`,
    //   textAlign: 'left',
    // },
    // td: {
    //   padding: `${vars.gap.SS} ${vars.gap.S}`,
    //   border: `1px solid ${palette.dark.extraLight}`,
    // },
  },
  { name: 'MdContent' },
);
